#!/usr/bin/env bash
# Update package list and install nginx


sudo apt update
sudo apt -y install nginx

sudo nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx reload
