#!/usr/bin/env bash
# Installs, configures, and starts the server

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

echo "Hello World" > /etc/nginx/html/index.html

# sets nginx to listen on port 80
printf %s "server {
	listen	80;
	listen	[::]:80 default server;
	root	/etc/nginx/html;
	index	index.html inde.htm;
}
" > /etc/nginx/sites-available/default

service nginx start
