#!/usr/bin/env bash
# configure nginx to redirect

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx to redirect /redirect_me
echo "location /redirect_me {" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
echo "    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
echo "}" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

sudo service nginx reload
