#!/usr/bin/env bash
# Installs Nginx with the following configurations:

sudo apt-get update
sudo apt-get install -y nginx

sudo nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

sudo service nginx reload
