#!/usr/bin/env bash
# This script creates a fictional story based on /etc/passwd.

while IFS=: read -r username _ gid _ home shell; do
  echo "The user $username is part of the gang with GROUP_ID $gid, lives in $home, and rides $shell."
  echo "USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
  echo
done < /etc/passwd
