#!/usr/bin/env bash
#This script displays "Best School" 10 times, with a special case on the 9th iteration

count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
